//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TKB_G9.G9Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="G9_ServiceSoap", Namespace="http://abc.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class G9_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTaiKhoanByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback KiemTraDangNhapOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDanhSachLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhatLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPhongByMaChiTietTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLopByMaChiTietTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListTKBByGiaoVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestCreateTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTKBFromLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDanhSachChiTietTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChiTietTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLopFromTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGiaoVienFromTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMonHocFromTKBOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public G9_Service() {
            this.Url = global::TKB_G9.Properties.Settings.Default.TKB_G9_G9Service_G9_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getTaiKhoanByUserNameCompletedEventHandler getTaiKhoanByUserNameCompleted;
        
        /// <remarks/>
        public event KiemTraDangNhapCompletedEventHandler KiemTraDangNhapCompleted;
        
        /// <remarks/>
        public event GetDanhSachLopCompletedEventHandler GetDanhSachLopCompleted;
        
        /// <remarks/>
        public event GetLopCompletedEventHandler GetLopCompleted;
        
        /// <remarks/>
        public event ThemLopCompletedEventHandler ThemLopCompleted;
        
        /// <remarks/>
        public event XoaLopCompletedEventHandler XoaLopCompleted;
        
        /// <remarks/>
        public event CapNhatLopCompletedEventHandler CapNhatLopCompleted;
        
        /// <remarks/>
        public event getPhongByMaChiTietTKBCompletedEventHandler getPhongByMaChiTietTKBCompleted;
        
        /// <remarks/>
        public event getLopByMaChiTietTKBCompletedEventHandler getLopByMaChiTietTKBCompleted;
        
        /// <remarks/>
        public event getListTKBByGiaoVienCompletedEventHandler getListTKBByGiaoVienCompleted;
        
        /// <remarks/>
        public event GenerateTKBCompletedEventHandler GenerateTKBCompleted;
        
        /// <remarks/>
        public event TestCreateTKBCompletedEventHandler TestCreateTKBCompleted;
        
        /// <remarks/>
        public event CreateTKBCompletedEventHandler CreateTKBCompleted;
        
        /// <remarks/>
        public event GetTKBCompletedEventHandler GetTKBCompleted;
        
        /// <remarks/>
        public event GetTKBFromLopCompletedEventHandler GetTKBFromLopCompleted;
        
        /// <remarks/>
        public event GetDanhSachChiTietTKBCompletedEventHandler GetDanhSachChiTietTKBCompleted;
        
        /// <remarks/>
        public event GetChiTietTKBCompletedEventHandler GetChiTietTKBCompleted;
        
        /// <remarks/>
        public event GetLopFromTKBCompletedEventHandler GetLopFromTKBCompleted;
        
        /// <remarks/>
        public event GetGiaoVienFromTKBCompletedEventHandler GetGiaoVienFromTKBCompleted;
        
        /// <remarks/>
        public event GetMonHocFromTKBCompletedEventHandler GetMonHocFromTKBCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/HelloWorld", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/getTaiKhoanByUserName", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaiKhoan getTaiKhoanByUserName(string userName) {
            object[] results = this.Invoke("getTaiKhoanByUserName", new object[] {
                        userName});
            return ((TaiKhoan)(results[0]));
        }
        
        /// <remarks/>
        public void getTaiKhoanByUserNameAsync(string userName) {
            this.getTaiKhoanByUserNameAsync(userName, null);
        }
        
        /// <remarks/>
        public void getTaiKhoanByUserNameAsync(string userName, object userState) {
            if ((this.getTaiKhoanByUserNameOperationCompleted == null)) {
                this.getTaiKhoanByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTaiKhoanByUserNameOperationCompleted);
            }
            this.InvokeAsync("getTaiKhoanByUserName", new object[] {
                        userName}, this.getTaiKhoanByUserNameOperationCompleted, userState);
        }
        
        private void OngetTaiKhoanByUserNameOperationCompleted(object arg) {
            if ((this.getTaiKhoanByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTaiKhoanByUserNameCompleted(this, new getTaiKhoanByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/KiemTraDangNhap", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KiemTraDangNhap(string user, string password) {
            object[] results = this.Invoke("KiemTraDangNhap", new object[] {
                        user,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KiemTraDangNhapAsync(string user, string password) {
            this.KiemTraDangNhapAsync(user, password, null);
        }
        
        /// <remarks/>
        public void KiemTraDangNhapAsync(string user, string password, object userState) {
            if ((this.KiemTraDangNhapOperationCompleted == null)) {
                this.KiemTraDangNhapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKiemTraDangNhapOperationCompleted);
            }
            this.InvokeAsync("KiemTraDangNhap", new object[] {
                        user,
                        password}, this.KiemTraDangNhapOperationCompleted, userState);
        }
        
        private void OnKiemTraDangNhapOperationCompleted(object arg) {
            if ((this.KiemTraDangNhapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KiemTraDangNhapCompleted(this, new KiemTraDangNhapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetDanhSachLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lop[] GetDanhSachLop() {
            object[] results = this.Invoke("GetDanhSachLop", new object[0]);
            return ((Lop[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDanhSachLopAsync() {
            this.GetDanhSachLopAsync(null);
        }
        
        /// <remarks/>
        public void GetDanhSachLopAsync(object userState) {
            if ((this.GetDanhSachLopOperationCompleted == null)) {
                this.GetDanhSachLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDanhSachLopOperationCompleted);
            }
            this.InvokeAsync("GetDanhSachLop", new object[0], this.GetDanhSachLopOperationCompleted, userState);
        }
        
        private void OnGetDanhSachLopOperationCompleted(object arg) {
            if ((this.GetDanhSachLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDanhSachLopCompleted(this, new GetDanhSachLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lop GetLop(int maLop) {
            object[] results = this.Invoke("GetLop", new object[] {
                        maLop});
            return ((Lop)(results[0]));
        }
        
        /// <remarks/>
        public void GetLopAsync(int maLop) {
            this.GetLopAsync(maLop, null);
        }
        
        /// <remarks/>
        public void GetLopAsync(int maLop, object userState) {
            if ((this.GetLopOperationCompleted == null)) {
                this.GetLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLopOperationCompleted);
            }
            this.InvokeAsync("GetLop", new object[] {
                        maLop}, this.GetLopOperationCompleted, userState);
        }
        
        private void OnGetLopOperationCompleted(object arg) {
            if ((this.GetLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLopCompleted(this, new GetLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/ThemLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemLop(Lop lop) {
            object[] results = this.Invoke("ThemLop", new object[] {
                        lop});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemLopAsync(Lop lop) {
            this.ThemLopAsync(lop, null);
        }
        
        /// <remarks/>
        public void ThemLopAsync(Lop lop, object userState) {
            if ((this.ThemLopOperationCompleted == null)) {
                this.ThemLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemLopOperationCompleted);
            }
            this.InvokeAsync("ThemLop", new object[] {
                        lop}, this.ThemLopOperationCompleted, userState);
        }
        
        private void OnThemLopOperationCompleted(object arg) {
            if ((this.ThemLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemLopCompleted(this, new ThemLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/XoaLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaLop(int maLop) {
            object[] results = this.Invoke("XoaLop", new object[] {
                        maLop});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaLopAsync(int maLop) {
            this.XoaLopAsync(maLop, null);
        }
        
        /// <remarks/>
        public void XoaLopAsync(int maLop, object userState) {
            if ((this.XoaLopOperationCompleted == null)) {
                this.XoaLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaLopOperationCompleted);
            }
            this.InvokeAsync("XoaLop", new object[] {
                        maLop}, this.XoaLopOperationCompleted, userState);
        }
        
        private void OnXoaLopOperationCompleted(object arg) {
            if ((this.XoaLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaLopCompleted(this, new XoaLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/CapNhatLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CapNhatLop(Lop lopClient) {
            object[] results = this.Invoke("CapNhatLop", new object[] {
                        lopClient});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhatLopAsync(Lop lopClient) {
            this.CapNhatLopAsync(lopClient, null);
        }
        
        /// <remarks/>
        public void CapNhatLopAsync(Lop lopClient, object userState) {
            if ((this.CapNhatLopOperationCompleted == null)) {
                this.CapNhatLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhatLopOperationCompleted);
            }
            this.InvokeAsync("CapNhatLop", new object[] {
                        lopClient}, this.CapNhatLopOperationCompleted, userState);
        }
        
        private void OnCapNhatLopOperationCompleted(object arg) {
            if ((this.CapNhatLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhatLopCompleted(this, new CapNhatLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/getPhongByMaChiTietTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Phong getPhongByMaChiTietTKB(int maCT) {
            object[] results = this.Invoke("getPhongByMaChiTietTKB", new object[] {
                        maCT});
            return ((Phong)(results[0]));
        }
        
        /// <remarks/>
        public void getPhongByMaChiTietTKBAsync(int maCT) {
            this.getPhongByMaChiTietTKBAsync(maCT, null);
        }
        
        /// <remarks/>
        public void getPhongByMaChiTietTKBAsync(int maCT, object userState) {
            if ((this.getPhongByMaChiTietTKBOperationCompleted == null)) {
                this.getPhongByMaChiTietTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPhongByMaChiTietTKBOperationCompleted);
            }
            this.InvokeAsync("getPhongByMaChiTietTKB", new object[] {
                        maCT}, this.getPhongByMaChiTietTKBOperationCompleted, userState);
        }
        
        private void OngetPhongByMaChiTietTKBOperationCompleted(object arg) {
            if ((this.getPhongByMaChiTietTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPhongByMaChiTietTKBCompleted(this, new getPhongByMaChiTietTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/getLopByMaChiTietTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lop getLopByMaChiTietTKB(int maCT) {
            object[] results = this.Invoke("getLopByMaChiTietTKB", new object[] {
                        maCT});
            return ((Lop)(results[0]));
        }
        
        /// <remarks/>
        public void getLopByMaChiTietTKBAsync(int maCT) {
            this.getLopByMaChiTietTKBAsync(maCT, null);
        }
        
        /// <remarks/>
        public void getLopByMaChiTietTKBAsync(int maCT, object userState) {
            if ((this.getLopByMaChiTietTKBOperationCompleted == null)) {
                this.getLopByMaChiTietTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLopByMaChiTietTKBOperationCompleted);
            }
            this.InvokeAsync("getLopByMaChiTietTKB", new object[] {
                        maCT}, this.getLopByMaChiTietTKBOperationCompleted, userState);
        }
        
        private void OngetLopByMaChiTietTKBOperationCompleted(object arg) {
            if ((this.getLopByMaChiTietTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLopByMaChiTietTKBCompleted(this, new getLopByMaChiTietTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/getListTKBByGiaoVien", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChiTietTKB[] getListTKBByGiaoVien(string tenTaiKhoan) {
            object[] results = this.Invoke("getListTKBByGiaoVien", new object[] {
                        tenTaiKhoan});
            return ((ChiTietTKB[])(results[0]));
        }
        
        /// <remarks/>
        public void getListTKBByGiaoVienAsync(string tenTaiKhoan) {
            this.getListTKBByGiaoVienAsync(tenTaiKhoan, null);
        }
        
        /// <remarks/>
        public void getListTKBByGiaoVienAsync(string tenTaiKhoan, object userState) {
            if ((this.getListTKBByGiaoVienOperationCompleted == null)) {
                this.getListTKBByGiaoVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListTKBByGiaoVienOperationCompleted);
            }
            this.InvokeAsync("getListTKBByGiaoVien", new object[] {
                        tenTaiKhoan}, this.getListTKBByGiaoVienOperationCompleted, userState);
        }
        
        private void OngetListTKBByGiaoVienOperationCompleted(object arg) {
            if ((this.getListTKBByGiaoVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListTKBByGiaoVienCompleted(this, new getListTKBByGiaoVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GenerateTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GenerateTKB(string namHoc, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfChiTietTKB")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] ChiTietTKB[][] arrTKB1, MonHoc[] dsMonHoc, Lop[] dsLop, Phong[] dsPhong, GiaoVien[] dsGiaoVien) {
            object[] results = this.Invoke("GenerateTKB", new object[] {
                        namHoc,
                        arrTKB1,
                        dsMonHoc,
                        dsLop,
                        dsPhong,
                        dsGiaoVien});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTKBAsync(string namHoc, ChiTietTKB[][] arrTKB1, MonHoc[] dsMonHoc, Lop[] dsLop, Phong[] dsPhong, GiaoVien[] dsGiaoVien) {
            this.GenerateTKBAsync(namHoc, arrTKB1, dsMonHoc, dsLop, dsPhong, dsGiaoVien, null);
        }
        
        /// <remarks/>
        public void GenerateTKBAsync(string namHoc, ChiTietTKB[][] arrTKB1, MonHoc[] dsMonHoc, Lop[] dsLop, Phong[] dsPhong, GiaoVien[] dsGiaoVien, object userState) {
            if ((this.GenerateTKBOperationCompleted == null)) {
                this.GenerateTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTKBOperationCompleted);
            }
            this.InvokeAsync("GenerateTKB", new object[] {
                        namHoc,
                        arrTKB1,
                        dsMonHoc,
                        dsLop,
                        dsPhong,
                        dsGiaoVien}, this.GenerateTKBOperationCompleted, userState);
        }
        
        private void OnGenerateTKBOperationCompleted(object arg) {
            if ((this.GenerateTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTKBCompleted(this, new GenerateTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/TestCreateTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TestCreateTKB() {
            object[] results = this.Invoke("TestCreateTKB", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TestCreateTKBAsync() {
            this.TestCreateTKBAsync(null);
        }
        
        /// <remarks/>
        public void TestCreateTKBAsync(object userState) {
            if ((this.TestCreateTKBOperationCompleted == null)) {
                this.TestCreateTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestCreateTKBOperationCompleted);
            }
            this.InvokeAsync("TestCreateTKB", new object[0], this.TestCreateTKBOperationCompleted, userState);
        }
        
        private void OnTestCreateTKBOperationCompleted(object arg) {
            if ((this.TestCreateTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCreateTKBCompleted(this, new TestCreateTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/CreateTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateTKB(Lop[] dsLop, string namHoc) {
            object[] results = this.Invoke("CreateTKB", new object[] {
                        dsLop,
                        namHoc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTKBAsync(Lop[] dsLop, string namHoc) {
            this.CreateTKBAsync(dsLop, namHoc, null);
        }
        
        /// <remarks/>
        public void CreateTKBAsync(Lop[] dsLop, string namHoc, object userState) {
            if ((this.CreateTKBOperationCompleted == null)) {
                this.CreateTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTKBOperationCompleted);
            }
            this.InvokeAsync("CreateTKB", new object[] {
                        dsLop,
                        namHoc}, this.CreateTKBOperationCompleted, userState);
        }
        
        private void OnCreateTKBOperationCompleted(object arg) {
            if ((this.CreateTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTKBCompleted(this, new CreateTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThoiKhoaBieu[] GetTKB(string namHoc) {
            object[] results = this.Invoke("GetTKB", new object[] {
                        namHoc});
            return ((ThoiKhoaBieu[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTKBAsync(string namHoc) {
            this.GetTKBAsync(namHoc, null);
        }
        
        /// <remarks/>
        public void GetTKBAsync(string namHoc, object userState) {
            if ((this.GetTKBOperationCompleted == null)) {
                this.GetTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTKBOperationCompleted);
            }
            this.InvokeAsync("GetTKB", new object[] {
                        namHoc}, this.GetTKBOperationCompleted, userState);
        }
        
        private void OnGetTKBOperationCompleted(object arg) {
            if ((this.GetTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTKBCompleted(this, new GetTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetTKBFromLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThoiKhoaBieu GetTKBFromLop(int maLop) {
            object[] results = this.Invoke("GetTKBFromLop", new object[] {
                        maLop});
            return ((ThoiKhoaBieu)(results[0]));
        }
        
        /// <remarks/>
        public void GetTKBFromLopAsync(int maLop) {
            this.GetTKBFromLopAsync(maLop, null);
        }
        
        /// <remarks/>
        public void GetTKBFromLopAsync(int maLop, object userState) {
            if ((this.GetTKBFromLopOperationCompleted == null)) {
                this.GetTKBFromLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTKBFromLopOperationCompleted);
            }
            this.InvokeAsync("GetTKBFromLop", new object[] {
                        maLop}, this.GetTKBFromLopOperationCompleted, userState);
        }
        
        private void OnGetTKBFromLopOperationCompleted(object arg) {
            if ((this.GetTKBFromLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTKBFromLopCompleted(this, new GetTKBFromLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetDanhSachChiTietTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChiTietTKB[] GetDanhSachChiTietTKB(int maTKB) {
            object[] results = this.Invoke("GetDanhSachChiTietTKB", new object[] {
                        maTKB});
            return ((ChiTietTKB[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDanhSachChiTietTKBAsync(int maTKB) {
            this.GetDanhSachChiTietTKBAsync(maTKB, null);
        }
        
        /// <remarks/>
        public void GetDanhSachChiTietTKBAsync(int maTKB, object userState) {
            if ((this.GetDanhSachChiTietTKBOperationCompleted == null)) {
                this.GetDanhSachChiTietTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDanhSachChiTietTKBOperationCompleted);
            }
            this.InvokeAsync("GetDanhSachChiTietTKB", new object[] {
                        maTKB}, this.GetDanhSachChiTietTKBOperationCompleted, userState);
        }
        
        private void OnGetDanhSachChiTietTKBOperationCompleted(object arg) {
            if ((this.GetDanhSachChiTietTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDanhSachChiTietTKBCompleted(this, new GetDanhSachChiTietTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetChiTietTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChiTietTKB GetChiTietTKB(int maChiTiet) {
            object[] results = this.Invoke("GetChiTietTKB", new object[] {
                        maChiTiet});
            return ((ChiTietTKB)(results[0]));
        }
        
        /// <remarks/>
        public void GetChiTietTKBAsync(int maChiTiet) {
            this.GetChiTietTKBAsync(maChiTiet, null);
        }
        
        /// <remarks/>
        public void GetChiTietTKBAsync(int maChiTiet, object userState) {
            if ((this.GetChiTietTKBOperationCompleted == null)) {
                this.GetChiTietTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChiTietTKBOperationCompleted);
            }
            this.InvokeAsync("GetChiTietTKB", new object[] {
                        maChiTiet}, this.GetChiTietTKBOperationCompleted, userState);
        }
        
        private void OnGetChiTietTKBOperationCompleted(object arg) {
            if ((this.GetChiTietTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChiTietTKBCompleted(this, new GetChiTietTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetLopFromTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lop GetLopFromTKB(int maTKB) {
            object[] results = this.Invoke("GetLopFromTKB", new object[] {
                        maTKB});
            return ((Lop)(results[0]));
        }
        
        /// <remarks/>
        public void GetLopFromTKBAsync(int maTKB) {
            this.GetLopFromTKBAsync(maTKB, null);
        }
        
        /// <remarks/>
        public void GetLopFromTKBAsync(int maTKB, object userState) {
            if ((this.GetLopFromTKBOperationCompleted == null)) {
                this.GetLopFromTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLopFromTKBOperationCompleted);
            }
            this.InvokeAsync("GetLopFromTKB", new object[] {
                        maTKB}, this.GetLopFromTKBOperationCompleted, userState);
        }
        
        private void OnGetLopFromTKBOperationCompleted(object arg) {
            if ((this.GetLopFromTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLopFromTKBCompleted(this, new GetLopFromTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetGiaoVienFromTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GiaoVien GetGiaoVienFromTKB(int maChiTiet) {
            object[] results = this.Invoke("GetGiaoVienFromTKB", new object[] {
                        maChiTiet});
            return ((GiaoVien)(results[0]));
        }
        
        /// <remarks/>
        public void GetGiaoVienFromTKBAsync(int maChiTiet) {
            this.GetGiaoVienFromTKBAsync(maChiTiet, null);
        }
        
        /// <remarks/>
        public void GetGiaoVienFromTKBAsync(int maChiTiet, object userState) {
            if ((this.GetGiaoVienFromTKBOperationCompleted == null)) {
                this.GetGiaoVienFromTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGiaoVienFromTKBOperationCompleted);
            }
            this.InvokeAsync("GetGiaoVienFromTKB", new object[] {
                        maChiTiet}, this.GetGiaoVienFromTKBOperationCompleted, userState);
        }
        
        private void OnGetGiaoVienFromTKBOperationCompleted(object arg) {
            if ((this.GetGiaoVienFromTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGiaoVienFromTKBCompleted(this, new GetGiaoVienFromTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetMonHocFromTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MonHoc GetMonHocFromTKB(int maChiTiet) {
            object[] results = this.Invoke("GetMonHocFromTKB", new object[] {
                        maChiTiet});
            return ((MonHoc)(results[0]));
        }
        
        /// <remarks/>
        public void GetMonHocFromTKBAsync(int maChiTiet) {
            this.GetMonHocFromTKBAsync(maChiTiet, null);
        }
        
        /// <remarks/>
        public void GetMonHocFromTKBAsync(int maChiTiet, object userState) {
            if ((this.GetMonHocFromTKBOperationCompleted == null)) {
                this.GetMonHocFromTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMonHocFromTKBOperationCompleted);
            }
            this.InvokeAsync("GetMonHocFromTKB", new object[] {
                        maChiTiet}, this.GetMonHocFromTKBOperationCompleted, userState);
        }
        
        private void OnGetMonHocFromTKBOperationCompleted(object arg) {
            if ((this.GetMonHocFromTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMonHocFromTKBCompleted(this, new GetMonHocFromTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class TaiKhoan : EntityObject {
        
        private int maTaiKhoanField;
        
        private string tenTaiKhoanField;
        
        private string matKhauField;
        
        private EntityReferenceOfLoaiTaiKhoan loaiTaiKhoanReferenceField;
        
        /// <remarks/>
        public int MaTaiKhoan {
            get {
                return this.maTaiKhoanField;
            }
            set {
                this.maTaiKhoanField = value;
            }
        }
        
        /// <remarks/>
        public string TenTaiKhoan {
            get {
                return this.tenTaiKhoanField;
            }
            set {
                this.tenTaiKhoanField = value;
            }
        }
        
        /// <remarks/>
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLoaiTaiKhoan LoaiTaiKhoanReference {
            get {
                return this.loaiTaiKhoanReferenceField;
            }
            set {
                this.loaiTaiKhoanReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLoaiTaiKhoan : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfGiaoVien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiTaiKhoan))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfGiaoVien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiTaiKhoan))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaiKhoan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GiaoVien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChiTietTKB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Lop))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaiKhoan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GiaoVien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChiTietTKB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Lop))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class ThoiKhoaBieu : EntityObject {
        
        private int maTKBField;
        
        private string namHocField;
        
        private EntityReferenceOfLop lopReferenceField;
        
        /// <remarks/>
        public int MaTKB {
            get {
                return this.maTKBField;
            }
            set {
                this.maTKBField = value;
            }
        }
        
        /// <remarks/>
        public string NamHoc {
            get {
                return this.namHocField;
            }
            set {
                this.namHocField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLop LopReference {
            get {
                return this.lopReferenceField;
            }
            set {
                this.lopReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLop : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class GiaoVien : EntityObject {
        
        private int maGiaoVienField;
        
        private string tenGiaoVienField;
        
        private string gioiTinhField;
        
        private System.Nullable<System.DateTime> ngaySinhField;
        
        private string diaChiField;
        
        private string dienThoaiField;
        
        private string emailField;
        
        private EntityReferenceOfMonHoc monHocReferenceField;
        
        /// <remarks/>
        public int MaGiaoVien {
            get {
                return this.maGiaoVienField;
            }
            set {
                this.maGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public string TenGiaoVien {
            get {
                return this.tenGiaoVienField;
            }
            set {
                this.tenGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public string GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string DienThoai {
            get {
                return this.dienThoaiField;
            }
            set {
                this.dienThoaiField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfMonHoc MonHocReference {
            get {
                return this.monHocReferenceField;
            }
            set {
                this.monHocReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfMonHoc : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class Phong : EntityObject {
        
        private int maPhongField;
        
        private string tenPhongField;
        
        private string tinhTrangField;
        
        private System.Nullable<int> sucChuaField;
        
        private EntityReferenceOfLoaiPhong loaiPhongReferenceField;
        
        /// <remarks/>
        public int MaPhong {
            get {
                return this.maPhongField;
            }
            set {
                this.maPhongField = value;
            }
        }
        
        /// <remarks/>
        public string TenPhong {
            get {
                return this.tenPhongField;
            }
            set {
                this.tenPhongField = value;
            }
        }
        
        /// <remarks/>
        public string TinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                this.tinhTrangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SucChua {
            get {
                return this.sucChuaField;
            }
            set {
                this.sucChuaField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLoaiPhong LoaiPhongReference {
            get {
                return this.loaiPhongReferenceField;
            }
            set {
                this.loaiPhongReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLoaiPhong : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class MonHoc : EntityObject {
        
        private int maMonHocField;
        
        private string tenMonHocField;
        
        private string moTaField;
        
        private System.Nullable<int> monChinhField;
        
        private System.Nullable<int> heSoMonHocField;
        
        private string ghiChuField;
        
        private System.Nullable<int> soTietField;
        
        private EntityReferenceOfLoaiMonHoc loaiMonHocReferenceField;
        
        /// <remarks/>
        public int MaMonHoc {
            get {
                return this.maMonHocField;
            }
            set {
                this.maMonHocField = value;
            }
        }
        
        /// <remarks/>
        public string TenMonHoc {
            get {
                return this.tenMonHocField;
            }
            set {
                this.tenMonHocField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MonChinh {
            get {
                return this.monChinhField;
            }
            set {
                this.monChinhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> HeSoMonHoc {
            get {
                return this.heSoMonHocField;
            }
            set {
                this.heSoMonHocField = value;
            }
        }
        
        /// <remarks/>
        public string GhiChu {
            get {
                return this.ghiChuField;
            }
            set {
                this.ghiChuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SoTiet {
            get {
                return this.soTietField;
            }
            set {
                this.soTietField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLoaiMonHoc LoaiMonHocReference {
            get {
                return this.loaiMonHocReferenceField;
            }
            set {
                this.loaiMonHocReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLoaiMonHoc : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class ChiTietTKB : EntityObject {
        
        private int maChiTietTKBField;
        
        private System.Nullable<int> tietBatDauField;
        
        private System.Nullable<int> tietKetThucField;
        
        private System.Nullable<int> thuField;
        
        private EntityReferenceOfGiaoVien giaoVienReferenceField;
        
        private EntityReferenceOfMonHoc monHocReferenceField;
        
        private EntityReferenceOfPhong phongReferenceField;
        
        private EntityReferenceOfThoiKhoaBieu thoiKhoaBieuReferenceField;
        
        /// <remarks/>
        public int MaChiTietTKB {
            get {
                return this.maChiTietTKBField;
            }
            set {
                this.maChiTietTKBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TietBatDau {
            get {
                return this.tietBatDauField;
            }
            set {
                this.tietBatDauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TietKetThuc {
            get {
                return this.tietKetThucField;
            }
            set {
                this.tietKetThucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Thu {
            get {
                return this.thuField;
            }
            set {
                this.thuField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfGiaoVien GiaoVienReference {
            get {
                return this.giaoVienReferenceField;
            }
            set {
                this.giaoVienReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfMonHoc MonHocReference {
            get {
                return this.monHocReferenceField;
            }
            set {
                this.monHocReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfPhong PhongReference {
            get {
                return this.phongReferenceField;
            }
            set {
                this.phongReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfThoiKhoaBieu ThoiKhoaBieuReference {
            get {
                return this.thoiKhoaBieuReferenceField;
            }
            set {
                this.thoiKhoaBieuReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfGiaoVien : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfPhong : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfThoiKhoaBieu : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class Lop : EntityObject {
        
        private int maLopField;
        
        private string tenLopField;
        
        private string khoiLopField;
        
        private string caHocField;
        
        private System.Nullable<int> siSoField;
        
        private string ghiChuField;
        
        /// <remarks/>
        public int MaLop {
            get {
                return this.maLopField;
            }
            set {
                this.maLopField = value;
            }
        }
        
        /// <remarks/>
        public string TenLop {
            get {
                return this.tenLopField;
            }
            set {
                this.tenLopField = value;
            }
        }
        
        /// <remarks/>
        public string KhoiLop {
            get {
                return this.khoiLopField;
            }
            set {
                this.khoiLopField = value;
            }
        }
        
        /// <remarks/>
        public string CaHoc {
            get {
                return this.caHocField;
            }
            set {
                this.caHocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SiSo {
            get {
                return this.siSoField;
            }
            set {
                this.siSoField = value;
            }
        }
        
        /// <remarks/>
        public string GhiChu {
            get {
                return this.ghiChuField;
            }
            set {
                this.ghiChuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTaiKhoanByUserNameCompletedEventHandler(object sender, getTaiKhoanByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTaiKhoanByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTaiKhoanByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaiKhoan Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaiKhoan)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KiemTraDangNhapCompletedEventHandler(object sender, KiemTraDangNhapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KiemTraDangNhapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KiemTraDangNhapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDanhSachLopCompletedEventHandler(object sender, GetDanhSachLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDanhSachLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDanhSachLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lop[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lop[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLopCompletedEventHandler(object sender, GetLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lop Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lop)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ThemLopCompletedEventHandler(object sender, ThemLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XoaLopCompletedEventHandler(object sender, XoaLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapNhatLopCompletedEventHandler(object sender, CapNhatLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhatLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhatLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPhongByMaChiTietTKBCompletedEventHandler(object sender, getPhongByMaChiTietTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPhongByMaChiTietTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPhongByMaChiTietTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Phong Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Phong)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getLopByMaChiTietTKBCompletedEventHandler(object sender, getLopByMaChiTietTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLopByMaChiTietTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLopByMaChiTietTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lop Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lop)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getListTKBByGiaoVienCompletedEventHandler(object sender, getListTKBByGiaoVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListTKBByGiaoVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListTKBByGiaoVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChiTietTKB[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChiTietTKB[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GenerateTKBCompletedEventHandler(object sender, GenerateTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TestCreateTKBCompletedEventHandler(object sender, TestCreateTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCreateTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCreateTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateTKBCompletedEventHandler(object sender, CreateTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTKBCompletedEventHandler(object sender, GetTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThoiKhoaBieu[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThoiKhoaBieu[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTKBFromLopCompletedEventHandler(object sender, GetTKBFromLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTKBFromLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTKBFromLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThoiKhoaBieu Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThoiKhoaBieu)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDanhSachChiTietTKBCompletedEventHandler(object sender, GetDanhSachChiTietTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDanhSachChiTietTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDanhSachChiTietTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChiTietTKB[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChiTietTKB[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetChiTietTKBCompletedEventHandler(object sender, GetChiTietTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChiTietTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChiTietTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChiTietTKB Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChiTietTKB)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLopFromTKBCompletedEventHandler(object sender, GetLopFromTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLopFromTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLopFromTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lop Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lop)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGiaoVienFromTKBCompletedEventHandler(object sender, GetGiaoVienFromTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGiaoVienFromTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGiaoVienFromTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GiaoVien Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GiaoVien)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMonHocFromTKBCompletedEventHandler(object sender, GetMonHocFromTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMonHocFromTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMonHocFromTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MonHoc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MonHoc)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591