//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_ChiTietTKB_GiaoVien", "GiaoVien", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.GiaoVien), "ChiTietTKB", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.ChiTietTKB))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_ChiTietTKB_MonHoc", "MonHoc", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.MonHoc), "ChiTietTKB", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.ChiTietTKB))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_ChiTietTKB_ThoiKhoaBieu", "ThoiKhoaBieu", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.ThoiKhoaBieu), "ChiTietTKB", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.ChiTietTKB))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_GiaoVien_LoaiGiaoVien", "LoaiGiaoVien", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.LoaiGiaoVien), "GiaoVien", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.GiaoVien))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_GiaoVien_MonHoc", "MonHoc", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.MonHoc), "GiaoVien", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.GiaoVien))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_HocSinh_LOP", "LOP", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.LOP), "HocSinh", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.HocSinh))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TKBModel", "FK_ThoiKhoaBieu_LOP", "LOP", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TKB_G9_Service.LOP), "ThoiKhoaBieu", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TKB_G9_Service.ThoiKhoaBieu))]

// Original file name:
// Generation date: 12/19/2012 2:55:52 PM
namespace TKB_G9_Service
{
    
    /// <summary>
    /// There are no comments for TKBEntities in the schema.
    /// </summary>
    public partial class TKBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TKBEntities object using the connection string found in the 'TKBEntities' section of the application configuration file.
        /// </summary>
        public TKBEntities() : 
                base("name=TKBEntities", "TKBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TKBEntities object.
        /// </summary>
        public TKBEntities(string connectionString) : 
                base(connectionString, "TKBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TKBEntities object.
        /// </summary>
        public TKBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TKBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ChiTietTKBs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ChiTietTKB> ChiTietTKBs
        {
            get
            {
                if ((this._ChiTietTKBs == null))
                {
                    this._ChiTietTKBs = base.CreateQuery<ChiTietTKB>("[ChiTietTKBs]");
                }
                return this._ChiTietTKBs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ChiTietTKB> _ChiTietTKBs;
        /// <summary>
        /// There are no comments for GiaoViens in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<GiaoVien> GiaoViens
        {
            get
            {
                if ((this._GiaoViens == null))
                {
                    this._GiaoViens = base.CreateQuery<GiaoVien>("[GiaoViens]");
                }
                return this._GiaoViens;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<GiaoVien> _GiaoViens;
        /// <summary>
        /// There are no comments for HocSinhs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<HocSinh> HocSinhs
        {
            get
            {
                if ((this._HocSinhs == null))
                {
                    this._HocSinhs = base.CreateQuery<HocSinh>("[HocSinhs]");
                }
                return this._HocSinhs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<HocSinh> _HocSinhs;
        /// <summary>
        /// There are no comments for LoaiGiaoViens in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<LoaiGiaoVien> LoaiGiaoViens
        {
            get
            {
                if ((this._LoaiGiaoViens == null))
                {
                    this._LoaiGiaoViens = base.CreateQuery<LoaiGiaoVien>("[LoaiGiaoViens]");
                }
                return this._LoaiGiaoViens;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<LoaiGiaoVien> _LoaiGiaoViens;
        /// <summary>
        /// There are no comments for LOPs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<LOP> LOPs
        {
            get
            {
                if ((this._LOPs == null))
                {
                    this._LOPs = base.CreateQuery<LOP>("[LOPs]");
                }
                return this._LOPs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<LOP> _LOPs;
        /// <summary>
        /// There are no comments for MonHocs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<MonHoc> MonHocs
        {
            get
            {
                if ((this._MonHocs == null))
                {
                    this._MonHocs = base.CreateQuery<MonHoc>("[MonHocs]");
                }
                return this._MonHocs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<MonHoc> _MonHocs;
        /// <summary>
        /// There are no comments for ThoiKhoaBieux in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ThoiKhoaBieu> ThoiKhoaBieux
        {
            get
            {
                if ((this._ThoiKhoaBieux == null))
                {
                    this._ThoiKhoaBieux = base.CreateQuery<ThoiKhoaBieu>("[ThoiKhoaBieux]");
                }
                return this._ThoiKhoaBieux;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ThoiKhoaBieu> _ThoiKhoaBieux;
        /// <summary>
        /// There are no comments for ChiTietTKBs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToChiTietTKBs(ChiTietTKB chiTietTKB)
        {
            base.AddObject("ChiTietTKBs", chiTietTKB);
        }
        /// <summary>
        /// There are no comments for GiaoViens in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToGiaoViens(GiaoVien giaoVien)
        {
            base.AddObject("GiaoViens", giaoVien);
        }
        /// <summary>
        /// There are no comments for HocSinhs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToHocSinhs(HocSinh hocSinh)
        {
            base.AddObject("HocSinhs", hocSinh);
        }
        /// <summary>
        /// There are no comments for LoaiGiaoViens in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToLoaiGiaoViens(LoaiGiaoVien loaiGiaoVien)
        {
            base.AddObject("LoaiGiaoViens", loaiGiaoVien);
        }
        /// <summary>
        /// There are no comments for LOPs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToLOPs(LOP lOP)
        {
            base.AddObject("LOPs", lOP);
        }
        /// <summary>
        /// There are no comments for MonHocs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMonHocs(MonHoc monHoc)
        {
            base.AddObject("MonHocs", monHoc);
        }
        /// <summary>
        /// There are no comments for ThoiKhoaBieux in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToThoiKhoaBieux(ThoiKhoaBieu thoiKhoaBieu)
        {
            base.AddObject("ThoiKhoaBieux", thoiKhoaBieu);
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.ChiTietTKB in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="ChiTietTKB")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ChiTietTKB : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ChiTietTKB object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ChiTietTKB CreateChiTietTKB(string id)
        {
            ChiTietTKB chiTietTKB = new ChiTietTKB();
            chiTietTKB.id = id;
            return chiTietTKB;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property GioBatDau in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string GioBatDau
        {
            get
            {
                return this._GioBatDau;
            }
            set
            {
                this.OnGioBatDauChanging(value);
                this.ReportPropertyChanging("GioBatDau");
                this._GioBatDau = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GioBatDau");
                this.OnGioBatDauChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _GioBatDau;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGioBatDauChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGioBatDauChanged();
        /// <summary>
        /// There are no comments for property GioKetThuc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string GioKetThuc
        {
            get
            {
                return this._GioKetThuc;
            }
            set
            {
                this.OnGioKetThucChanging(value);
                this.ReportPropertyChanging("GioKetThuc");
                this._GioKetThuc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GioKetThuc");
                this.OnGioKetThucChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _GioKetThuc;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGioKetThucChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGioKetThucChanged();
        /// <summary>
        /// There are no comments for GiaoVien in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ChiTietTKB_GiaoVien", "GiaoVien")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public GiaoVien GiaoVien
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GiaoVien>("TKBModel.FK_ChiTietTKB_GiaoVien", "GiaoVien").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GiaoVien>("TKBModel.FK_ChiTietTKB_GiaoVien", "GiaoVien").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for GiaoVien in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<GiaoVien> GiaoVienReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GiaoVien>("TKBModel.FK_ChiTietTKB_GiaoVien", "GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<GiaoVien>("TKBModel.FK_ChiTietTKB_GiaoVien", "GiaoVien", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MonHoc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ChiTietTKB_MonHoc", "MonHoc")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MonHoc MonHoc
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MonHoc>("TKBModel.FK_ChiTietTKB_MonHoc", "MonHoc").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MonHoc>("TKBModel.FK_ChiTietTKB_MonHoc", "MonHoc").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MonHoc in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MonHoc> MonHocReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MonHoc>("TKBModel.FK_ChiTietTKB_MonHoc", "MonHoc");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MonHoc>("TKBModel.FK_ChiTietTKB_MonHoc", "MonHoc", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ThoiKhoaBieu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ChiTietTKB_ThoiKhoaBieu", "ThoiKhoaBieu")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ThoiKhoaBieu ThoiKhoaBieu
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ThoiKhoaBieu>("TKBModel.FK_ChiTietTKB_ThoiKhoaBieu", "ThoiKhoaBieu").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ThoiKhoaBieu>("TKBModel.FK_ChiTietTKB_ThoiKhoaBieu", "ThoiKhoaBieu").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ThoiKhoaBieu in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ThoiKhoaBieu> ThoiKhoaBieuReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ThoiKhoaBieu>("TKBModel.FK_ChiTietTKB_ThoiKhoaBieu", "ThoiKhoaBieu");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ThoiKhoaBieu>("TKBModel.FK_ChiTietTKB_ThoiKhoaBieu", "ThoiKhoaBieu", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.GiaoVien in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="GiaoVien")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GiaoVien : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new GiaoVien object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static GiaoVien CreateGiaoVien(string id)
        {
            GiaoVien giaoVien = new GiaoVien();
            giaoVien.id = id;
            return giaoVien;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property TenGiaoVien in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TenGiaoVien
        {
            get
            {
                return this._TenGiaoVien;
            }
            set
            {
                this.OnTenGiaoVienChanging(value);
                this.ReportPropertyChanging("TenGiaoVien");
                this._TenGiaoVien = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TenGiaoVien");
                this.OnTenGiaoVienChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TenGiaoVien;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenGiaoVienChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenGiaoVienChanged();
        /// <summary>
        /// There are no comments for property ChuNhiem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ChuNhiem
        {
            get
            {
                return this._ChuNhiem;
            }
            set
            {
                this.OnChuNhiemChanging(value);
                this.ReportPropertyChanging("ChuNhiem");
                this._ChuNhiem = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ChuNhiem");
                this.OnChuNhiemChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ChuNhiem;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnChuNhiemChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnChuNhiemChanged();
        /// <summary>
        /// There are no comments for ChiTietTKBs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ChiTietTKB_GiaoVien", "ChiTietTKB")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ChiTietTKB> ChiTietTKBs
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ChiTietTKB>("TKBModel.FK_ChiTietTKB_GiaoVien", "ChiTietTKB");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ChiTietTKB>("TKBModel.FK_ChiTietTKB_GiaoVien", "ChiTietTKB", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for LoaiGiaoVien in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_GiaoVien_LoaiGiaoVien", "LoaiGiaoVien")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public LoaiGiaoVien LoaiGiaoVien
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LoaiGiaoVien>("TKBModel.FK_GiaoVien_LoaiGiaoVien", "LoaiGiaoVien").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LoaiGiaoVien>("TKBModel.FK_GiaoVien_LoaiGiaoVien", "LoaiGiaoVien").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for LoaiGiaoVien in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<LoaiGiaoVien> LoaiGiaoVienReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LoaiGiaoVien>("TKBModel.FK_GiaoVien_LoaiGiaoVien", "LoaiGiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<LoaiGiaoVien>("TKBModel.FK_GiaoVien_LoaiGiaoVien", "LoaiGiaoVien", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MonHoc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_GiaoVien_MonHoc", "MonHoc")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MonHoc MonHoc
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MonHoc>("TKBModel.FK_GiaoVien_MonHoc", "MonHoc").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MonHoc>("TKBModel.FK_GiaoVien_MonHoc", "MonHoc").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MonHoc in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MonHoc> MonHocReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MonHoc>("TKBModel.FK_GiaoVien_MonHoc", "MonHoc");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MonHoc>("TKBModel.FK_GiaoVien_MonHoc", "MonHoc", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.HocSinh in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="HocSinh")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class HocSinh : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new HocSinh object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static HocSinh CreateHocSinh(string id)
        {
            HocSinh hocSinh = new HocSinh();
            hocSinh.id = id;
            return hocSinh;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property TenHocSinh in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TenHocSinh
        {
            get
            {
                return this._TenHocSinh;
            }
            set
            {
                this.OnTenHocSinhChanging(value);
                this.ReportPropertyChanging("TenHocSinh");
                this._TenHocSinh = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TenHocSinh");
                this.OnTenHocSinhChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TenHocSinh;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenHocSinhChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenHocSinhChanged();
        /// <summary>
        /// There are no comments for property NgayNhapHoc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NgayNhapHoc
        {
            get
            {
                return this._NgayNhapHoc;
            }
            set
            {
                this.OnNgayNhapHocChanging(value);
                this.ReportPropertyChanging("NgayNhapHoc");
                this._NgayNhapHoc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NgayNhapHoc");
                this.OnNgayNhapHocChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NgayNhapHoc;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNgayNhapHocChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNgayNhapHocChanged();
        /// <summary>
        /// There are no comments for property DiaChi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DiaChi
        {
            get
            {
                return this._DiaChi;
            }
            set
            {
                this.OnDiaChiChanging(value);
                this.ReportPropertyChanging("DiaChi");
                this._DiaChi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DiaChi");
                this.OnDiaChiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DiaChi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDiaChiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDiaChiChanged();
        /// <summary>
        /// There are no comments for LOP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_HocSinh_LOP", "LOP")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public LOP LOP
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LOP>("TKBModel.FK_HocSinh_LOP", "LOP").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LOP>("TKBModel.FK_HocSinh_LOP", "LOP").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for LOP in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<LOP> LOPReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LOP>("TKBModel.FK_HocSinh_LOP", "LOP");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<LOP>("TKBModel.FK_HocSinh_LOP", "LOP", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.LoaiGiaoVien in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="LoaiGiaoVien")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LoaiGiaoVien : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LoaiGiaoVien object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static LoaiGiaoVien CreateLoaiGiaoVien(string id)
        {
            LoaiGiaoVien loaiGiaoVien = new LoaiGiaoVien();
            loaiGiaoVien.id = id;
            return loaiGiaoVien;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property TenLoaiGiaoVien in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TenLoaiGiaoVien
        {
            get
            {
                return this._TenLoaiGiaoVien;
            }
            set
            {
                this.OnTenLoaiGiaoVienChanging(value);
                this.ReportPropertyChanging("TenLoaiGiaoVien");
                this._TenLoaiGiaoVien = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TenLoaiGiaoVien");
                this.OnTenLoaiGiaoVienChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TenLoaiGiaoVien;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenLoaiGiaoVienChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenLoaiGiaoVienChanged();
        /// <summary>
        /// There are no comments for property ThoiHanHopDong in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ThoiHanHopDong
        {
            get
            {
                return this._ThoiHanHopDong;
            }
            set
            {
                this.OnThoiHanHopDongChanging(value);
                this.ReportPropertyChanging("ThoiHanHopDong");
                this._ThoiHanHopDong = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ThoiHanHopDong");
                this.OnThoiHanHopDongChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ThoiHanHopDong;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnThoiHanHopDongChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnThoiHanHopDongChanged();
        /// <summary>
        /// There are no comments for property NgayNhanViec in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NgayNhanViec
        {
            get
            {
                return this._NgayNhanViec;
            }
            set
            {
                this.OnNgayNhanViecChanging(value);
                this.ReportPropertyChanging("NgayNhanViec");
                this._NgayNhanViec = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NgayNhanViec");
                this.OnNgayNhanViecChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NgayNhanViec;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNgayNhanViecChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNgayNhanViecChanged();
        /// <summary>
        /// There are no comments for GiaoViens in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_GiaoVien_LoaiGiaoVien", "GiaoVien")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GiaoVien> GiaoViens
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GiaoVien>("TKBModel.FK_GiaoVien_LoaiGiaoVien", "GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GiaoVien>("TKBModel.FK_GiaoVien_LoaiGiaoVien", "GiaoVien", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.LOP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="LOP")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LOP : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LOP object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static LOP CreateLOP(string id)
        {
            LOP lOP = new LOP();
            lOP.id = id;
            return lOP;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property TenLop in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TenLop
        {
            get
            {
                return this._TenLop;
            }
            set
            {
                this.OnTenLopChanging(value);
                this.ReportPropertyChanging("TenLop");
                this._TenLop = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TenLop");
                this.OnTenLopChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TenLop;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenLopChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenLopChanged();
        /// <summary>
        /// There are no comments for HocSinhs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_HocSinh_LOP", "HocSinh")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<HocSinh> HocSinhs
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<HocSinh>("TKBModel.FK_HocSinh_LOP", "HocSinh");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<HocSinh>("TKBModel.FK_HocSinh_LOP", "HocSinh", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ThoiKhoaBieux in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ThoiKhoaBieu_LOP", "ThoiKhoaBieu")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ThoiKhoaBieu> ThoiKhoaBieux
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ThoiKhoaBieu>("TKBModel.FK_ThoiKhoaBieu_LOP", "ThoiKhoaBieu");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ThoiKhoaBieu>("TKBModel.FK_ThoiKhoaBieu_LOP", "ThoiKhoaBieu", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.MonHoc in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="MonHoc")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MonHoc : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MonHoc object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static MonHoc CreateMonHoc(string id)
        {
            MonHoc monHoc = new MonHoc();
            monHoc.id = id;
            return monHoc;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property TenMonHoc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TenMonHoc
        {
            get
            {
                return this._TenMonHoc;
            }
            set
            {
                this.OnTenMonHocChanging(value);
                this.ReportPropertyChanging("TenMonHoc");
                this._TenMonHoc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TenMonHoc");
                this.OnTenMonHocChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TenMonHoc;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenMonHocChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTenMonHocChanged();
        /// <summary>
        /// There are no comments for property MoTa in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string MoTa
        {
            get
            {
                return this._MoTa;
            }
            set
            {
                this.OnMoTaChanging(value);
                this.ReportPropertyChanging("MoTa");
                this._MoTa = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MoTa");
                this.OnMoTaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _MoTa;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMoTaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMoTaChanged();
        /// <summary>
        /// There are no comments for ChiTietTKBs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ChiTietTKB_MonHoc", "ChiTietTKB")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ChiTietTKB> ChiTietTKBs
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ChiTietTKB>("TKBModel.FK_ChiTietTKB_MonHoc", "ChiTietTKB");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ChiTietTKB>("TKBModel.FK_ChiTietTKB_MonHoc", "ChiTietTKB", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for GiaoViens in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_GiaoVien_MonHoc", "GiaoVien")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GiaoVien> GiaoViens
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GiaoVien>("TKBModel.FK_GiaoVien_MonHoc", "GiaoVien");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GiaoVien>("TKBModel.FK_GiaoVien_MonHoc", "GiaoVien", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TKBModel.ThoiKhoaBieu in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TKBModel", Name="ThoiKhoaBieu")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThoiKhoaBieu : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThoiKhoaBieu object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ThoiKhoaBieu CreateThoiKhoaBieu(string id)
        {
            ThoiKhoaBieu thoiKhoaBieu = new ThoiKhoaBieu();
            thoiKhoaBieu.id = id;
            return thoiKhoaBieu;
        }
        /// <summary>
        /// There are no comments for property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for property NamHoc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NamHoc
        {
            get
            {
                return this._NamHoc;
            }
            set
            {
                this.OnNamHocChanging(value);
                this.ReportPropertyChanging("NamHoc");
                this._NamHoc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NamHoc");
                this.OnNamHocChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NamHoc;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNamHocChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNamHocChanged();
        /// <summary>
        /// There are no comments for ChiTietTKBs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ChiTietTKB_ThoiKhoaBieu", "ChiTietTKB")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ChiTietTKB> ChiTietTKBs
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ChiTietTKB>("TKBModel.FK_ChiTietTKB_ThoiKhoaBieu", "ChiTietTKB");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ChiTietTKB>("TKBModel.FK_ChiTietTKB_ThoiKhoaBieu", "ChiTietTKB", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for LOP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TKBModel", "FK_ThoiKhoaBieu_LOP", "LOP")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public LOP LOP
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LOP>("TKBModel.FK_ThoiKhoaBieu_LOP", "LOP").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LOP>("TKBModel.FK_ThoiKhoaBieu_LOP", "LOP").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for LOP in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<LOP> LOPReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LOP>("TKBModel.FK_ThoiKhoaBieu_LOP", "LOP");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<LOP>("TKBModel.FK_ThoiKhoaBieu_LOP", "LOP", value);
                }
            }
        }
    }
}
