//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TKB_G9.G9Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="G9_ServiceSoap", Namespace="http://abc.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Lop[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class G9_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback KiemTraDangNhapOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDanhSachLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestCreateTKBOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public G9_Service() {
            this.Url = global::TKB_G9.Properties.Settings.Default.TKB_G9_G9Service_G9_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event KiemTraDangNhapCompletedEventHandler KiemTraDangNhapCompleted;
        
        /// <remarks/>
        public event GetDanhSachLopCompletedEventHandler GetDanhSachLopCompleted;
        
        /// <remarks/>
        public event CreateTKBCompletedEventHandler CreateTKBCompleted;
        
        /// <remarks/>
        public event TestCreateTKBCompletedEventHandler TestCreateTKBCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/HelloWorld", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/KiemTraDangNhap", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KiemTraDangNhap(string user, string password) {
            object[] results = this.Invoke("KiemTraDangNhap", new object[] {
                        user,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KiemTraDangNhapAsync(string user, string password) {
            this.KiemTraDangNhapAsync(user, password, null);
        }
        
        /// <remarks/>
        public void KiemTraDangNhapAsync(string user, string password, object userState) {
            if ((this.KiemTraDangNhapOperationCompleted == null)) {
                this.KiemTraDangNhapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKiemTraDangNhapOperationCompleted);
            }
            this.InvokeAsync("KiemTraDangNhap", new object[] {
                        user,
                        password}, this.KiemTraDangNhapOperationCompleted, userState);
        }
        
        private void OnKiemTraDangNhapOperationCompleted(object arg) {
            if ((this.KiemTraDangNhapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KiemTraDangNhapCompleted(this, new KiemTraDangNhapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/GetDanhSachLop", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lop[] GetDanhSachLop() {
            object[] results = this.Invoke("GetDanhSachLop", new object[0]);
            return ((Lop[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDanhSachLopAsync() {
            this.GetDanhSachLopAsync(null);
        }
        
        /// <remarks/>
        public void GetDanhSachLopAsync(object userState) {
            if ((this.GetDanhSachLopOperationCompleted == null)) {
                this.GetDanhSachLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDanhSachLopOperationCompleted);
            }
            this.InvokeAsync("GetDanhSachLop", new object[0], this.GetDanhSachLopOperationCompleted, userState);
        }
        
        private void OnGetDanhSachLopOperationCompleted(object arg) {
            if ((this.GetDanhSachLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDanhSachLopCompleted(this, new GetDanhSachLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/CreateTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThoiKhoaBieu[] CreateTKB(string namHoc, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfChiTietTKB")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] ChiTietTKB[][] arrTKB1, MonHoc[] dsMonHoc, Lop[] dsLop, Phong[] dsPhong, GiaoVien[] dsGiaoVien) {
            object[] results = this.Invoke("CreateTKB", new object[] {
                        namHoc,
                        arrTKB1,
                        dsMonHoc,
                        dsLop,
                        dsPhong,
                        dsGiaoVien});
            return ((ThoiKhoaBieu[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateTKBAsync(string namHoc, ChiTietTKB[][] arrTKB1, MonHoc[] dsMonHoc, Lop[] dsLop, Phong[] dsPhong, GiaoVien[] dsGiaoVien) {
            this.CreateTKBAsync(namHoc, arrTKB1, dsMonHoc, dsLop, dsPhong, dsGiaoVien, null);
        }
        
        /// <remarks/>
        public void CreateTKBAsync(string namHoc, ChiTietTKB[][] arrTKB1, MonHoc[] dsMonHoc, Lop[] dsLop, Phong[] dsPhong, GiaoVien[] dsGiaoVien, object userState) {
            if ((this.CreateTKBOperationCompleted == null)) {
                this.CreateTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTKBOperationCompleted);
            }
            this.InvokeAsync("CreateTKB", new object[] {
                        namHoc,
                        arrTKB1,
                        dsMonHoc,
                        dsLop,
                        dsPhong,
                        dsGiaoVien}, this.CreateTKBOperationCompleted, userState);
        }
        
        private void OnCreateTKBOperationCompleted(object arg) {
            if ((this.CreateTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTKBCompleted(this, new CreateTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abc.com/TestCreateTKB", RequestNamespace="http://abc.com/", ResponseNamespace="http://abc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThoiKhoaBieu[] TestCreateTKB() {
            object[] results = this.Invoke("TestCreateTKB", new object[0]);
            return ((ThoiKhoaBieu[])(results[0]));
        }
        
        /// <remarks/>
        public void TestCreateTKBAsync() {
            this.TestCreateTKBAsync(null);
        }
        
        /// <remarks/>
        public void TestCreateTKBAsync(object userState) {
            if ((this.TestCreateTKBOperationCompleted == null)) {
                this.TestCreateTKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestCreateTKBOperationCompleted);
            }
            this.InvokeAsync("TestCreateTKB", new object[0], this.TestCreateTKBOperationCompleted, userState);
        }
        
        private void OnTestCreateTKBOperationCompleted(object arg) {
            if ((this.TestCreateTKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCreateTKBCompleted(this, new TestCreateTKBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class Lop : EntityObject {
        
        private int maLopField;
        
        private string tenLopField;
        
        private string khoiLopField;
        
        private string caHocField;
        
        private System.Nullable<int> siSoField;
        
        private string ghiChuField;
        
        /// <remarks/>
        public int MaLop {
            get {
                return this.maLopField;
            }
            set {
                this.maLopField = value;
            }
        }
        
        /// <remarks/>
        public string TenLop {
            get {
                return this.tenLopField;
            }
            set {
                this.tenLopField = value;
            }
        }
        
        /// <remarks/>
        public string KhoiLop {
            get {
                return this.khoiLopField;
            }
            set {
                this.khoiLopField = value;
            }
        }
        
        /// <remarks/>
        public string CaHoc {
            get {
                return this.caHocField;
            }
            set {
                this.caHocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SiSo {
            get {
                return this.siSoField;
            }
            set {
                this.siSoField = value;
            }
        }
        
        /// <remarks/>
        public string GhiChu {
            get {
                return this.ghiChuField;
            }
            set {
                this.ghiChuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GiaoVien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChiTietTKB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Lop))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfGiaoVien))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiMonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoaiPhong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfGiaoVien))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfMonHoc : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfPhong : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfThoiKhoaBieu : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLoaiMonHoc : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLoaiPhong : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfLop : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class EntityReferenceOfGiaoVien : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThoiKhoaBieu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GiaoVien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phong))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MonHoc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChiTietTKB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Lop))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class ThoiKhoaBieu : EntityObject {
        
        private int maTKBField;
        
        private string namHocField;
        
        private EntityReferenceOfLop lopReferenceField;
        
        /// <remarks/>
        public int MaTKB {
            get {
                return this.maTKBField;
            }
            set {
                this.maTKBField = value;
            }
        }
        
        /// <remarks/>
        public string NamHoc {
            get {
                return this.namHocField;
            }
            set {
                this.namHocField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLop LopReference {
            get {
                return this.lopReferenceField;
            }
            set {
                this.lopReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class GiaoVien : EntityObject {
        
        private int maGiaoVienField;
        
        private string tenGiaoVienField;
        
        private string gioiTinhField;
        
        private System.Nullable<System.DateTime> ngaySinhField;
        
        private string diaChiField;
        
        private string dienThoaiField;
        
        private string emailField;
        
        private EntityReferenceOfMonHoc monHocReferenceField;
        
        /// <remarks/>
        public int MaGiaoVien {
            get {
                return this.maGiaoVienField;
            }
            set {
                this.maGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public string TenGiaoVien {
            get {
                return this.tenGiaoVienField;
            }
            set {
                this.tenGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public string GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string DienThoai {
            get {
                return this.dienThoaiField;
            }
            set {
                this.dienThoaiField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfMonHoc MonHocReference {
            get {
                return this.monHocReferenceField;
            }
            set {
                this.monHocReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class Phong : EntityObject {
        
        private int maPhongField;
        
        private string tenPhongField;
        
        private string tinhTrangField;
        
        private System.Nullable<int> sucChuaField;
        
        private EntityReferenceOfLoaiPhong loaiPhongReferenceField;
        
        /// <remarks/>
        public int MaPhong {
            get {
                return this.maPhongField;
            }
            set {
                this.maPhongField = value;
            }
        }
        
        /// <remarks/>
        public string TenPhong {
            get {
                return this.tenPhongField;
            }
            set {
                this.tenPhongField = value;
            }
        }
        
        /// <remarks/>
        public string TinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                this.tinhTrangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SucChua {
            get {
                return this.sucChuaField;
            }
            set {
                this.sucChuaField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLoaiPhong LoaiPhongReference {
            get {
                return this.loaiPhongReferenceField;
            }
            set {
                this.loaiPhongReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class MonHoc : EntityObject {
        
        private int maMonHocField;
        
        private string tenMonHocField;
        
        private string moTaField;
        
        private System.Nullable<int> monChinhField;
        
        private System.Nullable<int> heSoMonHocField;
        
        private string ghiChuField;
        
        private System.Nullable<int> soTietField;
        
        private EntityReferenceOfLoaiMonHoc loaiMonHocReferenceField;
        
        /// <remarks/>
        public int MaMonHoc {
            get {
                return this.maMonHocField;
            }
            set {
                this.maMonHocField = value;
            }
        }
        
        /// <remarks/>
        public string TenMonHoc {
            get {
                return this.tenMonHocField;
            }
            set {
                this.tenMonHocField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MonChinh {
            get {
                return this.monChinhField;
            }
            set {
                this.monChinhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> HeSoMonHoc {
            get {
                return this.heSoMonHocField;
            }
            set {
                this.heSoMonHocField = value;
            }
        }
        
        /// <remarks/>
        public string GhiChu {
            get {
                return this.ghiChuField;
            }
            set {
                this.ghiChuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SoTiet {
            get {
                return this.soTietField;
            }
            set {
                this.soTietField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLoaiMonHoc LoaiMonHocReference {
            get {
                return this.loaiMonHocReferenceField;
            }
            set {
                this.loaiMonHocReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://abc.com/")]
    public partial class ChiTietTKB : EntityObject {
        
        private int maChiTietTKBField;
        
        private System.Nullable<int> tietBatDauField;
        
        private System.Nullable<int> tietKetThucField;
        
        private System.Nullable<int> thuField;
        
        private EntityReferenceOfGiaoVien giaoVienReferenceField;
        
        private EntityReferenceOfMonHoc monHocReferenceField;
        
        private EntityReferenceOfPhong phongReferenceField;
        
        private EntityReferenceOfThoiKhoaBieu thoiKhoaBieuReferenceField;
        
        /// <remarks/>
        public int MaChiTietTKB {
            get {
                return this.maChiTietTKBField;
            }
            set {
                this.maChiTietTKBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TietBatDau {
            get {
                return this.tietBatDauField;
            }
            set {
                this.tietBatDauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TietKetThuc {
            get {
                return this.tietKetThucField;
            }
            set {
                this.tietKetThucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Thu {
            get {
                return this.thuField;
            }
            set {
                this.thuField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfGiaoVien GiaoVienReference {
            get {
                return this.giaoVienReferenceField;
            }
            set {
                this.giaoVienReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfMonHoc MonHocReference {
            get {
                return this.monHocReferenceField;
            }
            set {
                this.monHocReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfPhong PhongReference {
            get {
                return this.phongReferenceField;
            }
            set {
                this.phongReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfThoiKhoaBieu ThoiKhoaBieuReference {
            get {
                return this.thoiKhoaBieuReferenceField;
            }
            set {
                this.thoiKhoaBieuReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KiemTraDangNhapCompletedEventHandler(object sender, KiemTraDangNhapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KiemTraDangNhapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KiemTraDangNhapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDanhSachLopCompletedEventHandler(object sender, GetDanhSachLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDanhSachLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDanhSachLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lop[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lop[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateTKBCompletedEventHandler(object sender, CreateTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThoiKhoaBieu[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThoiKhoaBieu[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TestCreateTKBCompletedEventHandler(object sender, TestCreateTKBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCreateTKBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCreateTKBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThoiKhoaBieu[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThoiKhoaBieu[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591